[project]
name = "course-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "playwright>=1.56.0",
]

[tool.uv.workspace]
members = [
    "bs4",
]
